config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  get 'store/index'
  get 'home/home'

  get 'sign_up', to: 'registrations#new'
  post "sign_up", to: "registrations#create"
  
  root to: 'home#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email adress"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    flash.now[:notice] = "Logged in successfully"
    flash.now[:alert] = "invalid email or password"
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController 
    def new
        user = User.new
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/home/home.html.erb
<div class="relative isolate px-6 pt-14 lg:px-8">

    </div>
    <div class="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56">
      <div class="hidden sm:mb-8 sm:flex sm:justify-center">
        <div class="relative rounded-full px-3 py-1 text-sm leading-6 text-gray-600 ring-1 ring-gray-900/10 hover:ring-gray-900/20">
          NEU: Finnland & Brasilien 🇫🇮🇧🇷  <a href="#" class="font-semibold text-indigo-600"><span class="absolute inset-0" aria-hidden="true"></span>Jetzt entdecken <span aria-hidden="true">&rarr;</span></a>
        </div>
      </div>
      <div class="text-center">
        <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">🌴Travelshop.de🌴</h1>
        <p class="mt-1 text-lg leading-29 text-gray-100">Deine Adresse für unvergessliche Momente</p>
        <br>
        <p class="mt-6 text-lg leading-8 text-gray-600">Hör auf zu warten und fang an zu leben! Bei Travelshop.de ist die perfekte Traumreise nur wenige Klicks entfernt. Unser Angebot enthält hunderte Reiseziele in 22 Ländern.</p>
        <div class="mt-10 flex items-center justify-center gap-x-6">
          <a href="#" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Reise buchen</a>
          <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Angebote entdecken <span aria-hidden="true">→</span></a>
        </div>
      </div>
    </div>
    <div class="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80" aria-hidden="true">
        <div class="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)">
      </div>
    <div class="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-10rem)]" aria-hidden="true">
      <div class="relative left-[calc(50%+3rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(80%+66rem)] sm:w-[62.1875rem]" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
    </div>
  </div>
</div>

<br>
<br>
<br>

    <div class="absolute inset-x-20 -top-80 -z-10 transform-gpu overflow-hidden blur-0xl sm:-top-160" aria-hidden="true">
        <div class="aspect-[455/678] w-[136.15rem] -translate-x-2/1 bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%-30rem)] sm:w-[82.175rem]">
          <img src="https://th.bing.com/th/id/R.3126cc67c6926e358340c3be0a20f940?rik=NwY8PTQnn2G%2biQ&riu=http%3a%2f%2fimg.ev.mu%2fimages%2fportfolio%2fpays%2f186%2f1605x1070%2f852235.jpg&ehk=b3ZaxfWpxY%2bVY7wGbLtAqv5EwsFceo5k7JIZfrNevU8%3d&risl=&pid=ImgRaw&r=0" width="5000" height="6000">
      </div>
      </div>
      <br>
      <br>
      <div class="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56">
        <div class="text-center">
          <h1 class="text-4xl font-bold tracking-tight sm:-top-80 text-gray-900 sm:text-6xl">Réunion Aktiv</h1>
          <br>
          <p class="mt-6 text-lg leading-8 text-gray-100">14 Tage Action pur - von Canyoning in den steilen Kluften bis Surfen auf den sonnengetränkten Wellen. Und das alles auf einer der schönsten und abenteuerlichsten Inseln des indischen Ozeans. Worauf wartest du noch?</p>
          <br>
          <p>Inklusive Unterkunft und Verpflegung</p>
          <p>Maximal 5 Personen</p>
          <p>Hinfahrt und Rückfahrt nicht im Preis enthalten</p>
          <h3 class="text-4xl font-bold tracking-tight sm:-top-80 text-gray-900 sm:text-6xl" style="color:rgb(6, 100, 37);">nur 699,-€</h3>
          <div class="mt-10 flex items-center justify-center gap-x-6">
            <img src="/assets/reunion1.png" width="232" height="200"/>
            <img src="/assets/reunion2.jpeg" width="267" height="200"/>
            <img src="/assets/reunion3.jpeg" width="300" height="200"/>
          </div>
          <br>
          <br>
          <a href="#" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">In den Warenkorb</a>
        </div>
      </div>
    </div>

    <br>
    <br>
    <br>
    <br>
    <br>

    <div class="mt-1 absolute inset-x-50 -top-180 -z-10 transform-gpu overflow-hidden blur-0xl sm:-top-160" aria-hidden="true">
        <div class="aspect-[555/878] w-[136.15rem] -translate-x-2/1 bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(30%-130rem)] sm:w-[182.175rem]">
          <img src="https://franks-travelbox.com/wp-content/uploads/2017/11/kuba-havanna-das-capitolio-nacional-ein-an-die-hundert-meter-hoher-kuppelbau-wurde-dem-kapitol-in-washington-d-c-nachempfunden-havanna-kuba-regien-paassen-shutterstock.jpg" width="5000" height="6000">
      </div>
      </div>
      <br>
      <br>
      <div class="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56">
        <div class="text-center">
          <h1 class="text-4xl font-bold tracking-tight sm:-top-80 text-gray-900 sm:text-6xl">Kuba Stadt&Strand</h1>
          <br>
          <p class="mt-6 text-lg leading-8 text-gray-100">Der Entspannungsurlaub für alle Karibik-Connoisseure. Erlebe die kubanische Lebensart in den Städten und die karibische Sonne am Strand. Für eine angenehme Unterkunft in den besten Hotels der Insel ist ebenfalls gesorgt.</p>
          <br>
          <p>Inklusive Unterkunft und Verpflegung</p>
          <p>14 Tage aufenthalt an drei Orten</p>
          <p>Hinfahrt und Rückfahrt nicht im Preis enthalten</p>
          <h3 class="text-4xl font-bold tracking-tight sm:-top-80 text-gray-900 sm:text-6xl" style="color:rgb(6, 100, 37);">nur 799,-€</h3>
          <div class="mt-10 flex items-center justify-center gap-x-6">
            <img src="/assets/kuba1.jpeg" width="300" height="200"/>
            <img src="/assets/kuba2.jpg" width="300" height="200"/>
            <img src="/assets/kuba3.jpg" width="300" height="200"/>
          </div>
          <br>
          <br>
          <a href="#" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">In den Warenkorb</a>
        </div>
      </div>
    </div>

    <br>
<br>
<br>
<br>
<br>

    <div class="mt-1 absolute inset-x-50 -top-180 -z-10 transform-gpu overflow-hidden blur-0xl sm:-top-160" aria-hidden="true">
        <div class="aspect-[555/878] w-[136.15rem] -translate-x-2/1 bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(30%-130rem)] sm:w-[182.175rem]">
          <img src="https://www.exploring-umbria.com/wp-content/uploads/2019/05/SPELLO-PORTA-VENERE-TORRI-PROPERZIO.jpg" width="5000" height="6000">
      </div>
      </div>
      <br>
      <br>
      <div class="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56">
        <div class="text-center">
          <h1 class="text-4xl font-bold tracking-tight sm:-top-80 text-gray-900 sm:text-6xl">Italien Kultur</h1>
          <br>
          <p class="mt-6 text-lg leading-8 text-gray-100">Italien kann mehr als nur Pasta und Pizza. Das Land im Süden Europas steckt voller Geheimnisse und zahlreicher fantastischer Orte, die nur darauf warten von dir entdeckt zu werden.</p>
          <br>
          <p>Inklusive Unterkunft und Verpflegung</p>
          <p>14 Tage aufenthalt an 12 Stationen</p>
          <p>Hinfahrt und Rückfahrt nicht im Preis enthalten</p>
          <h3 class="text-4xl font-bold tracking-tight sm:-top-80 text-gray-900 sm:text-6xl" style="color:rgb(6, 100, 37);">nur 499,-€</h3>
          <div class="mt-10 flex items-center justify-center gap-x-6">
            <img src="/assets/italien.jpeg" width="300" height="200"/>
            <img src="/assets/italien2.jpeg" width="300" height="200"/>
            <img src="/assets/italien3.jpg" width="300" height="200"/>
          </div>
          <br>
          <br>
          <a href="#" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">In den Warenkorb</a>
        </div>
      </div>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travelshop.de</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%=render("shared/navbar")%>
    <div class="container">
      <%=render("shared/flash")%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<div>
    <div class="antialiased bg-gray-100">
        <div class="w-full text-gray-700 bg-white">
            <div class="flex flex-col max-w-screen-xl px-4 mx-auto md:items-center md:justify-between md:flex-row md:px-6 lg:px-8">
                <div class="flex flex-row items-center justify-between p-4">
                    <%= link_to "Travelshop.de", root_path, class: 'text-lg font-semibold tracking-widest text-gray-988 uppercase rounded-lg focus:outline-none focus: shadow-outline'%>
                </div>
                <nav class="flex-col flex-grow hidden pb-4 md:pb-0 md:flex md:justify-end md:flex-row">
                    <% nav_item_class = "px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg md:mt-0 md:ml-4 hover:text-gay-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-20 focus:outline-none focus:shadow-outline"%>
                    <%= link_to "Angebote", root_path, class: nav_item_class %>
                    <%= link_to "🛒 {0}€", sign_up_path, class: nav_item_class %>
                    <%= link_to "Account", sign_up_path, class: nav_item_class %>
                </nav>
            </div>
        </div>
    </div>
</div>

app/views/store/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Store#index</h1>
  <p>Find me in app/views/store/index.html.erb</p>
</div>